version: '3'
services:
 
  auth:
    container_name: auth
    image: golang:1.21.4
  
    depends_on:
       - postgres
      #  - rabbitmq
    environment:
      ENVIRONMENT: development
    volumes:
      - ./:/app/
    working_dir: /app
    expose:
      - 8180
      # - 8183
    ports:
      - '8180:8180'
      # - '8183:8183'
    command: >
     bash -c "go run ./cmd/main.go --config=./internal/config/config_local.yaml"
    #  go get && 

  postgres:
    container_name: postgres
    image: postgres:16.1-alpine3.19

    environment:
     POSTGRES_DB: auth
     POSTGRES_USER:  user
     POSTGRES_PASSWORD: user
    ports:
      - '5432:5432'
    volumes:
      - ./../db:/var/lib/postgresql
    healthcheck:
      test: pg_isready -U user -d auth
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 60s

  migrate:
    container_name: migrate
    image: migrate/migrate:v4.17.0
    volumes:
      - ./migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database",
        "postgres://user:user@postgres:5432/auth?sslmode=disable",
        "up"
      ]
    depends_on:
       - postgres